create table if not exists "users" (
  "id" bigint generated by default as identity primary key,
  "name" text,
  "email" text unique,
  "phone" text,
  "password" text,
  "createdAt" timestamptz,
  "profileImageKey" text
);

create table if not exists "transactions" (
  "id" bigint generated by default as identity primary key,
  "userId" bigint,
  "type" text,
  "category" text,
  "amount" numeric,
  "memo" text,
  "date" date,
  "goalId" bigint
);

create table if not exists "couples" (
  "id" bigint generated by default as identity primary key,
  "user1Id" bigint,
  "user2Id" bigint,
  "status" boolean default true,
  "createdAt" timestamptz,
  "userStatusMessage" text,
  "partnerStatusMessage" text
);

create table if not exists "coupleRequests" (
  "id" bigint generated by default as identity primary key,
  "fromId" bigint,
  "toId" bigint,
  "status" text,
  "createdAt" timestamptz
);

create table if not exists "coupleGoals" (
  "id" bigint generated by default as identity primary key,
  "coupleId" bigint,
  "type" text,
  "title" text,
  "targetAmount" numeric,
  "startDate" date,
  "endDate" date,
  "categories" jsonb default '[]'::jsonb,
  "category" text,
  "createdAt" timestamptz
);

create table if not exists "categories" (
  "id" bigint generated by default as identity primary key,
  "income" jsonb default '[]'::jsonb,
  "expense" jsonb default '[]'::jsonb
);

insert into "categories" ("id", "income", "expense")
values (
  1,
  '["급여", "부수입", "기타", "커플"]'::jsonb,
  '["식비", "교통/차량", "주거/통신", "쇼핑/생활", "의료/건강", "문화/여가", "기타"]'::jsonb
)
on conflict ("id") do nothing;

alter table "users" disable row level security;
alter table "transactions" disable row level security;
alter table "couples" disable row level security;
alter table "coupleRequests" disable row level security;
alter table "coupleGoals" disable row level security;
alter table "categories" disable row level security;
